### ISSUE TITLE
Internal error occurs

### ISSUE THREAD

**Issue by SinghNanak** [clear-code/redmine-plugin-wiki-change-notifier#2]
Thin_redmine & Thin_redmine2 crashes

**Comment by kou** [comment]
What are Thin_redmine and Thin_redmine2?

Could you show the followings?
* How to install this plugin
* How to reproduce this problem
* Full error log

**Comment by SinghNanak** [comment]
I'm using Bitnami Redmine on windows. I use the following method to install this plugin :

cd apps\redmine\htdocs
bundle install --without development test --no-deployment
bundle exec rake redmine:plugins RAILS_ENV=production

**Comment by SinghNanak** [comment]
I'm hoping that this plugin will notifies users with updated page of wiki.

**Comment by kou** [comment]
Could you also show full error log?

**Comment by SinghNanak** [comment]
can you share a screenshot of the mail you receive from this email.

**Comment by kou** [comment]
Why?

If you don't want to show full error log, can we close this?

**Comment by SinghNanak** [comment]
wait, the purpose of this plugin is to show content of wiki in email or something else

**Comment by kou** [comment]
Unified diff of Wiki changes is included in an email.

Can we close this now?

**Comment by SinghNanak** [comment]
oh i see, one last thing is there any way to send html of Unified diff of Wiki changes instead of link or both

**Comment by kou** [comment]
Both by  default.

I close this as not reproducible.
